### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/automatic-memory#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by dje750** [comment]
Hi

**Comment by MauriceJULIOT** [comment]
Hi

**Comment by GuillaumeDR57** [comment]
My comment @githubteacher

**Comment by de242admin** [comment]
Thanks

**Comment by ludovic-dbg** [comment]
What a nice doc

**Comment by ewaucq** [comment]
A comment

**Comment by hj350** [comment]
Hi

**Comment by elemiegre** [comment]
test

**Comment by PZ416** [comment]
hi

**Comment by wilslow** [comment]
hola

**Comment by vq783** [comment]
hi

**Comment by yw528git** [comment]
Test comment

**Comment by ta474** [comment]
helllo

**Comment by qk886** [comment]
coucou

**Comment by Treverer** [comment]
Hi

**Comment by wr971** [comment]
Add a new comment

**Comment by yw528git** [comment]
NC

**Comment by mg428** [comment]
here
